import time
import random
import logging
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from fastapi.responses import Response

# Import the validation pipeline built in Task 3
from feature_validator import FeatureValidationPipeline

# Setup Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("MLEndpoint")

# Initialize FastAPI app
app = FastAPI(
    title="Global Mobility ML Inference API",
    description="A monitored ML endpoint for predicting visa application success probabilities.",
    version="1.0.0"
)

# Enable CORS so the HTML frontend can connect to this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the Feature Validator
validator = FeatureValidationPipeline()

# --- Prometheus Monitoring Metrics ---
REQUEST_COUNT = Counter(
    "ml_inference_requests_total",
    "Total number of inference requests",
    ["method", "endpoint", "status"]
)

INFERENCE_LATENCY = Histogram(
    "ml_inference_latency_seconds",
    "Time spent processing inference requests",
    ["endpoint"]
)

PREDICTION_SCORE = Histogram(
    "ml_model_prediction_score",
    "Distribution of output probability scores generated by the model",
    buckets=[0.1, 0.3, 0.5, 0.7, 0.9, 1.0]
)


# --- Middleware for monitoring ---
@app.middleware("http")
async def monitor_requests(request: Request, call_next):
    start_time = time.time()
    
    # Process the request
    response = await call_next(request)
    
    # Calculate Latency
    latency = time.time() - start_time
    
    # Record Metrics
    REQUEST_COUNT.labels(method=request.method, endpoint=request.url.path, status=response.status_code).inc()
    
    if request.url.path == "/predict":
        INFERENCE_LATENCY.labels(endpoint="/predict").observe(latency)
        
    return response


# --- Endpoints ---
@app.get("/health")
def health_check():
    """Basic health check endpoint for load balancers."""
    return {"status": "healthy", "model_version": "v2.1.0-prod"}

@app.get("/metrics")
def get_metrics():
    """Exposes Prometheus metrics for scraping."""
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

@app.post("/predict")
def predict(payload: dict):
    """
    Main ML Inference Endpoint.
    1. Validates incoming features.
    2. Runs model inference.
    3. Returns prediction & logs metrics.
    """
    logger.info("Received request on /predict endpoint")
    
    # Step 1: Feature Validation
    is_valid, validated_data, errors = validator.run_validation(payload)
    if not is_valid:
        logger.warning(f"Validation failed: {errors}")
        raise HTTPException(status_code=400, detail={"validation_errors": errors})
    
    # Step 2: Model Inference Simulation
    time.sleep(random.uniform(0.1, 0.4)) # Simulate model execution delay
    
    score = 45
    exp = validated_data.get('experience', 0)
    if exp > 3: score += 15
    if exp > 8: score += 10
    
    skills = [s.lower() for s in validated_data.get('skills', [])]
    high_demand = ['python', 'machine learning', 'software engineering', 'ai', 'data science']
    if any(skill in high_demand for skill in skills):
        score += 25
        
    if validated_data.get('visaType') == 'skilled_worker':
        score += 5
        
    score += random.randint(-5, 5)
    final_prob = max(10, min(98, score)) / 100.0
    
    risk = "LOW" if final_prob >= 0.75 else "MEDIUM" if final_prob >= 0.50 else "HIGH"

    # Step 3: Record Model Specific Metrics
    PREDICTION_SCORE.observe(final_prob)
    
    logger.info(f"Inference complete. Probability: {final_prob}, Risk: {risk}")
    
    return {
        "status": "success",
        "predictions": {
            "approval_probability": final_prob,
            "risk_category": risk
        },
        "metadata": {
            "model_version": "v2.1.0-prod",
            "processing_time_ms": round(random.uniform(100, 400), 2)
        }
    }

# Entry point to run locally
if __name__ == "__main__":
    import uvicorn
    logger.info("Starting Monitored ML Endpoint on port 8000")
    uvicorn.run("app:app", host="127.0.0.1", port=8000, reload=True)
